# SPDX-FileCopyrightText: 2026 Helio Chissini de Castro <heliocastro@gmail.com>
# SPDX-FileCopyrightText: 2026 CARIAD SE
# SPDX-License-Identifier: MIT


from license_expression import ExpressionError, get_spdx_licensing
from pydantic import BaseModel, ConfigDict, Field, field_validator

from .provenance import ArtifactProvenance, RepositoryProvenance
from .text_location import TextLocation


class Snippet(BaseModel):
    """
    A code snippet detected by a snippet scanner, together with its provenance,
    license and additional scanner specific metadata.
    """

    model_config = ConfigDict(extra="forbid")

    score: float = Field(
        ...,
        description=(
            "The matching score between the code being scanned and the code "
            "snippet. This is scanner-specific (e.g. for ScanOSS this is a "
            "percentage)."
        ),
    )
    location: TextLocation = Field(
        ...,
        description="The text location in the snippet that has matched.",
    )
    provenance: RepositoryProvenance | ArtifactProvenance = Field(
        ...,
        description="The provenance of the snippet, either an artifact or a repository.",
    )
    purl: str = Field(
        ...,
        description="The purl representing the author/vendor, artifact, version of the "
        "code snippet. If the snippet scanner does not natively support "
        "purls, it will be generated by ORT.",
    )
    license: str = Field(
        ...,
        description="The SPDX license expression of the component the code snippet is coming from.",
    )
    additional_data: dict[str, str] = Field(
        default_factory=dict,
        description=(
            "A map for scanner-specific snippet data that cannot be mapped "
            "into any generalized property, but still needs to be made "
            "available in the scan summary."
        ),
    )

    def __hash__(self) -> int:
        return hash(self.purl)

    def __eq__(self, other) -> bool:
        if not isinstance(other, Snippet):
            return NotImplemented
        return self.purl == other.purl

    @field_validator("license", mode="before")
    @classmethod
    def validate_spdx(cls, value):
        try:
            licensing = get_spdx_licensing()
            licensing.parse(value)
            return value
        except ExpressionError as e:
            raise ValueError(f"Invalid SPDX license expression: {e}") from e
