# SPDX-FileCopyrightText: 2025 Helio Chissini de Castro <heliocastro@gmail.com>
#
# SPDX-License-Identifier: MIT

name: Validation
permissions:
  contents: read
  pull-requests: write

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches: [main]

jobs:
  commitlint:
    name: Commit Lint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: webiny/action-conventional-commits@faccb24fc2550dd15c0390d944379d2d8ed9690e # v1.3.1

  typecheck:
    needs: commitlint
    name: ty Type Checker
    runs-on: ubuntu-24.04

    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0
        with:
          enable-cache: true
          activate-environment: "true"
          python-version: "3.13"

      - name: Run ty Type Checker
        run: |
          uv sync
          uv run ty check --output-format github

  ruff:
    needs: commitlint
    name: Ruff Python Linter
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Ruff Check
        uses: astral-sh/ruff-action@0ce1b0bf8b818ef400413f810f8a11cdbda0034b
        with:
          args: 'check --config pyproject.toml'
      - name: Ruff Format
        uses: astral-sh/ruff-action@0ce1b0bf8b818ef400413f810f8a11cdbda0034b
        with:
          args: 'format --check --config pyproject.toml'
