# SPDX-FileCopyrightText: 2025 Helio Chissini de Castro <heliocastro@gmail.com>
#
# SPDX-License-Identifier: MIT

name: Publish

on:
  workflow_run:
    workflows:
      - Build
    types:
      - completed
  push:
    tags:
      - 'v*'
    paths-ignore:
      - '**.md'

jobs:
  publish:
    name: Publish Python Ort on PyPI
    runs-on: ubuntu-24.04
    environment:
      name: PyPI
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6.8.0
        with:
          enable-cache: true

      - uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38
        with:
          python-version: '3.10' # Minimal supported Python

      - name: Build 📦 package
        shell: bash
        run: |
          uv build

      - name: Upload artifacts
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08
        with:
          name: 'build-artifacts-python-3.13'
          path: dist/*

      - name: Publish PyPI 📦 package
        shell: bash
        run: |
          uv publish
